# Generated by Django 3.2.3 on 2021-11-01 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_contacted', models.BooleanField(default=True)),
                ('time_contacted', models.DateTimeField(blank=True, default='', null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
