# Generated by Django 3.2.3 on 2021-11-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211101_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner',
            field=models.FileField(blank=True, default='', null=True, upload_to='banners'),
        ),
    ]
